Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -47,6 +47,10 @@ jobs:
         run: npx playwright install --with-deps
       - name: Run Playwright tests
         run: npx playwright test
+      - name: Debug directory contents
+        run: |
+          ls -R playwright-report || echo "playwright-report directory not found"
+          ls -R test-results || echo "test-results directory not found"
       - name: Archive tests results
         if: success() || failure()
         uses: actions/upload-artifact@v3
@@ -55,10 +59,7 @@ jobs:
           path: |
             playwright-report/**
             test-results/**
-      - name: Debug directory contents
-        run: |
-          ls -R playwright-report || echo "playwright-report directory not found"
-          ls -R test-results || echo "test-results directory not found"
+
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure()
